/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerLoginRouteImport } from './routes/owner.login'
import { Route as OwnerDashboardRouteImport } from './routes/owner.dashboard'
import { Route as OwnerSubmissionsIndexRouteImport } from './routes/owner.submissions.index'
import { Route as OwnerSettingsIndexRouteImport } from './routes/owner.settings.index'
import { Route as OwnerSubmissionsIdRouteImport } from './routes/owner.submissions.$id'
import { Route as OwnerSettingsRoomsRouteImport } from './routes/owner.settings.rooms'
import { Route as OwnerSettingsPropertyRouteImport } from './routes/owner.settings.property'
import { Route as OwnerSettingsPaymentsRouteImport } from './routes/owner.settings.payments'
import { Route as OwnerSettingsPasswordsRouteImport } from './routes/owner.settings.passwords'
import { Route as OwnerSettingsHouseRulesRouteImport } from './routes/owner.settings.house-rules'
import { Route as OwnerSettingsGuideRouteImport } from './routes/owner.settings.guide'
import { Route as OwnerSettingsFaqRouteImport } from './routes/owner.settings.faq'
import { Route as OwnerSettingsExtraFeesRouteImport } from './routes/owner.settings.extra-fees'
import { Route as OwnerSettingsDepositRouteImport } from './routes/owner.settings.deposit'
import { Route as CheckinDemoSubmittedRouteImport } from './routes/checkin.demo.submitted'
import { Route as CheckinDemoStartRouteImport } from './routes/checkin.demo.start'
import { Route as CheckinDemoReviewRouteImport } from './routes/checkin.demo.review'
import { Route as CheckinDemoIdUploadRouteImport } from './routes/checkin.demo.id-upload'
import { Route as CheckinDemoHouseRulesRouteImport } from './routes/checkin.demo.house-rules'
import { Route as CheckinDemoHomeRouteImport } from './routes/checkin.demo.home'
import { Route as CheckinDemoGuideRouteImport } from './routes/checkin.demo.guide'
import { Route as CheckinDemoGuestInfoRouteImport } from './routes/checkin.demo.guest-info'
import { Route as CheckinDemoFaqRouteImport } from './routes/checkin.demo.faq'
import { Route as CheckinDemoDepositRouteImport } from './routes/checkin.demo.deposit'
import { Route as CheckinDemoBookingRouteImport } from './routes/checkin.demo.booking'
import { Route as CheckinDemoSurchargeIdRouteImport } from './routes/checkin.demo.surcharge.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner/login',
  path: '/owner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSubmissionsIndexRoute = OwnerSubmissionsIndexRouteImport.update({
  id: '/owner/submissions/',
  path: '/owner/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsIndexRoute = OwnerSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerSettingsRoute,
} as any)
const OwnerSubmissionsIdRoute = OwnerSubmissionsIdRouteImport.update({
  id: '/owner/submissions/$id',
  path: '/owner/submissions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoomsRoute = OwnerSettingsRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => OwnerSettingsRoute,
} as any)
const OwnerSettingsPropertyRoute = OwnerSettingsPropertyRouteImport.update({
  id: '/property',
  path: '/property',
  getParentRoute: () => OwnerSettingsRoute,
} as any)
const OwnerSettingsPaymentsRoute = OwnerSettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OwnerSettingsRoute,
} as any)
const OwnerSettingsPasswordsRoute = OwnerSettingsPasswordsRouteImport.update({
  id: '/passwords',
  path: '/passwords',
  getParentRoute: () => OwnerSettingsRoute,
} as any)
const OwnerSettingsHouseRulesRoute = OwnerSettingsHouseRulesRouteImport.update({
  id: '/house-rules',
  path: '/house-rules',
  getParentRoute: () => OwnerSettingsRoute,
} as any)
const OwnerSettingsGuideRoute = OwnerSettingsGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => OwnerSettingsRoute,
} as any)
const OwnerSettingsFaqRoute = OwnerSettingsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => OwnerSettingsRoute,
} as any)
const OwnerSettingsExtraFeesRoute = OwnerSettingsExtraFeesRouteImport.update({
  id: '/extra-fees',
  path: '/extra-fees',
  getParentRoute: () => OwnerSettingsRoute,
} as any)
const OwnerSettingsDepositRoute = OwnerSettingsDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => OwnerSettingsRoute,
} as any)
const CheckinDemoSubmittedRoute = CheckinDemoSubmittedRouteImport.update({
  id: '/checkin/demo/submitted',
  path: '/checkin/demo/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinDemoStartRoute = CheckinDemoStartRouteImport.update({
  id: '/checkin/demo/start',
  path: '/checkin/demo/start',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinDemoReviewRoute = CheckinDemoReviewRouteImport.update({
  id: '/checkin/demo/review',
  path: '/checkin/demo/review',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinDemoIdUploadRoute = CheckinDemoIdUploadRouteImport.update({
  id: '/checkin/demo/id-upload',
  path: '/checkin/demo/id-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinDemoHouseRulesRoute = CheckinDemoHouseRulesRouteImport.update({
  id: '/checkin/demo/house-rules',
  path: '/checkin/demo/house-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinDemoHomeRoute = CheckinDemoHomeRouteImport.update({
  id: '/checkin/demo/home',
  path: '/checkin/demo/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinDemoGuideRoute = CheckinDemoGuideRouteImport.update({
  id: '/checkin/demo/guide',
  path: '/checkin/demo/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinDemoGuestInfoRoute = CheckinDemoGuestInfoRouteImport.update({
  id: '/checkin/demo/guest-info',
  path: '/checkin/demo/guest-info',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinDemoFaqRoute = CheckinDemoFaqRouteImport.update({
  id: '/checkin/demo/faq',
  path: '/checkin/demo/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinDemoDepositRoute = CheckinDemoDepositRouteImport.update({
  id: '/checkin/demo/deposit',
  path: '/checkin/demo/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinDemoBookingRoute = CheckinDemoBookingRouteImport.update({
  id: '/checkin/demo/booking',
  path: '/checkin/demo/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinDemoSurchargeIdRoute = CheckinDemoSurchargeIdRouteImport.update({
  id: '/checkin/demo/surcharge/$id',
  path: '/checkin/demo/surcharge/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/settings': typeof OwnerSettingsRouteWithChildren
  '/owner/': typeof OwnerIndexRoute
  '/checkin/demo/booking': typeof CheckinDemoBookingRoute
  '/checkin/demo/deposit': typeof CheckinDemoDepositRoute
  '/checkin/demo/faq': typeof CheckinDemoFaqRoute
  '/checkin/demo/guest-info': typeof CheckinDemoGuestInfoRoute
  '/checkin/demo/guide': typeof CheckinDemoGuideRoute
  '/checkin/demo/home': typeof CheckinDemoHomeRoute
  '/checkin/demo/house-rules': typeof CheckinDemoHouseRulesRoute
  '/checkin/demo/id-upload': typeof CheckinDemoIdUploadRoute
  '/checkin/demo/review': typeof CheckinDemoReviewRoute
  '/checkin/demo/start': typeof CheckinDemoStartRoute
  '/checkin/demo/submitted': typeof CheckinDemoSubmittedRoute
  '/owner/settings/deposit': typeof OwnerSettingsDepositRoute
  '/owner/settings/extra-fees': typeof OwnerSettingsExtraFeesRoute
  '/owner/settings/faq': typeof OwnerSettingsFaqRoute
  '/owner/settings/guide': typeof OwnerSettingsGuideRoute
  '/owner/settings/house-rules': typeof OwnerSettingsHouseRulesRoute
  '/owner/settings/passwords': typeof OwnerSettingsPasswordsRoute
  '/owner/settings/payments': typeof OwnerSettingsPaymentsRoute
  '/owner/settings/property': typeof OwnerSettingsPropertyRoute
  '/owner/settings/rooms': typeof OwnerSettingsRoomsRoute
  '/owner/submissions/$id': typeof OwnerSubmissionsIdRoute
  '/owner/settings/': typeof OwnerSettingsIndexRoute
  '/owner/submissions/': typeof OwnerSubmissionsIndexRoute
  '/checkin/demo/surcharge/$id': typeof CheckinDemoSurchargeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner': typeof OwnerIndexRoute
  '/checkin/demo/booking': typeof CheckinDemoBookingRoute
  '/checkin/demo/deposit': typeof CheckinDemoDepositRoute
  '/checkin/demo/faq': typeof CheckinDemoFaqRoute
  '/checkin/demo/guest-info': typeof CheckinDemoGuestInfoRoute
  '/checkin/demo/guide': typeof CheckinDemoGuideRoute
  '/checkin/demo/home': typeof CheckinDemoHomeRoute
  '/checkin/demo/house-rules': typeof CheckinDemoHouseRulesRoute
  '/checkin/demo/id-upload': typeof CheckinDemoIdUploadRoute
  '/checkin/demo/review': typeof CheckinDemoReviewRoute
  '/checkin/demo/start': typeof CheckinDemoStartRoute
  '/checkin/demo/submitted': typeof CheckinDemoSubmittedRoute
  '/owner/settings/deposit': typeof OwnerSettingsDepositRoute
  '/owner/settings/extra-fees': typeof OwnerSettingsExtraFeesRoute
  '/owner/settings/faq': typeof OwnerSettingsFaqRoute
  '/owner/settings/guide': typeof OwnerSettingsGuideRoute
  '/owner/settings/house-rules': typeof OwnerSettingsHouseRulesRoute
  '/owner/settings/passwords': typeof OwnerSettingsPasswordsRoute
  '/owner/settings/payments': typeof OwnerSettingsPaymentsRoute
  '/owner/settings/property': typeof OwnerSettingsPropertyRoute
  '/owner/settings/rooms': typeof OwnerSettingsRoomsRoute
  '/owner/submissions/$id': typeof OwnerSubmissionsIdRoute
  '/owner/settings': typeof OwnerSettingsIndexRoute
  '/owner/submissions': typeof OwnerSubmissionsIndexRoute
  '/checkin/demo/surcharge/$id': typeof CheckinDemoSurchargeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/settings': typeof OwnerSettingsRouteWithChildren
  '/owner/': typeof OwnerIndexRoute
  '/checkin/demo/booking': typeof CheckinDemoBookingRoute
  '/checkin/demo/deposit': typeof CheckinDemoDepositRoute
  '/checkin/demo/faq': typeof CheckinDemoFaqRoute
  '/checkin/demo/guest-info': typeof CheckinDemoGuestInfoRoute
  '/checkin/demo/guide': typeof CheckinDemoGuideRoute
  '/checkin/demo/home': typeof CheckinDemoHomeRoute
  '/checkin/demo/house-rules': typeof CheckinDemoHouseRulesRoute
  '/checkin/demo/id-upload': typeof CheckinDemoIdUploadRoute
  '/checkin/demo/review': typeof CheckinDemoReviewRoute
  '/checkin/demo/start': typeof CheckinDemoStartRoute
  '/checkin/demo/submitted': typeof CheckinDemoSubmittedRoute
  '/owner/settings/deposit': typeof OwnerSettingsDepositRoute
  '/owner/settings/extra-fees': typeof OwnerSettingsExtraFeesRoute
  '/owner/settings/faq': typeof OwnerSettingsFaqRoute
  '/owner/settings/guide': typeof OwnerSettingsGuideRoute
  '/owner/settings/house-rules': typeof OwnerSettingsHouseRulesRoute
  '/owner/settings/passwords': typeof OwnerSettingsPasswordsRoute
  '/owner/settings/payments': typeof OwnerSettingsPaymentsRoute
  '/owner/settings/property': typeof OwnerSettingsPropertyRoute
  '/owner/settings/rooms': typeof OwnerSettingsRoomsRoute
  '/owner/submissions/$id': typeof OwnerSubmissionsIdRoute
  '/owner/settings/': typeof OwnerSettingsIndexRoute
  '/owner/submissions/': typeof OwnerSubmissionsIndexRoute
  '/checkin/demo/surcharge/$id': typeof CheckinDemoSurchargeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/owner/dashboard'
    | '/owner/login'
    | '/owner/settings'
    | '/owner/'
    | '/checkin/demo/booking'
    | '/checkin/demo/deposit'
    | '/checkin/demo/faq'
    | '/checkin/demo/guest-info'
    | '/checkin/demo/guide'
    | '/checkin/demo/home'
    | '/checkin/demo/house-rules'
    | '/checkin/demo/id-upload'
    | '/checkin/demo/review'
    | '/checkin/demo/start'
    | '/checkin/demo/submitted'
    | '/owner/settings/deposit'
    | '/owner/settings/extra-fees'
    | '/owner/settings/faq'
    | '/owner/settings/guide'
    | '/owner/settings/house-rules'
    | '/owner/settings/passwords'
    | '/owner/settings/payments'
    | '/owner/settings/property'
    | '/owner/settings/rooms'
    | '/owner/submissions/$id'
    | '/owner/settings/'
    | '/owner/submissions/'
    | '/checkin/demo/surcharge/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/owner/dashboard'
    | '/owner/login'
    | '/owner'
    | '/checkin/demo/booking'
    | '/checkin/demo/deposit'
    | '/checkin/demo/faq'
    | '/checkin/demo/guest-info'
    | '/checkin/demo/guide'
    | '/checkin/demo/home'
    | '/checkin/demo/house-rules'
    | '/checkin/demo/id-upload'
    | '/checkin/demo/review'
    | '/checkin/demo/start'
    | '/checkin/demo/submitted'
    | '/owner/settings/deposit'
    | '/owner/settings/extra-fees'
    | '/owner/settings/faq'
    | '/owner/settings/guide'
    | '/owner/settings/house-rules'
    | '/owner/settings/passwords'
    | '/owner/settings/payments'
    | '/owner/settings/property'
    | '/owner/settings/rooms'
    | '/owner/submissions/$id'
    | '/owner/settings'
    | '/owner/submissions'
    | '/checkin/demo/surcharge/$id'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/owner/dashboard'
    | '/owner/login'
    | '/owner/settings'
    | '/owner/'
    | '/checkin/demo/booking'
    | '/checkin/demo/deposit'
    | '/checkin/demo/faq'
    | '/checkin/demo/guest-info'
    | '/checkin/demo/guide'
    | '/checkin/demo/home'
    | '/checkin/demo/house-rules'
    | '/checkin/demo/id-upload'
    | '/checkin/demo/review'
    | '/checkin/demo/start'
    | '/checkin/demo/submitted'
    | '/owner/settings/deposit'
    | '/owner/settings/extra-fees'
    | '/owner/settings/faq'
    | '/owner/settings/guide'
    | '/owner/settings/house-rules'
    | '/owner/settings/passwords'
    | '/owner/settings/payments'
    | '/owner/settings/property'
    | '/owner/settings/rooms'
    | '/owner/submissions/$id'
    | '/owner/settings/'
    | '/owner/submissions/'
    | '/checkin/demo/surcharge/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerLoginRoute: typeof OwnerLoginRoute
  OwnerSettingsRoute: typeof OwnerSettingsRouteWithChildren
  OwnerIndexRoute: typeof OwnerIndexRoute
  CheckinDemoBookingRoute: typeof CheckinDemoBookingRoute
  CheckinDemoDepositRoute: typeof CheckinDemoDepositRoute
  CheckinDemoFaqRoute: typeof CheckinDemoFaqRoute
  CheckinDemoGuestInfoRoute: typeof CheckinDemoGuestInfoRoute
  CheckinDemoGuideRoute: typeof CheckinDemoGuideRoute
  CheckinDemoHomeRoute: typeof CheckinDemoHomeRoute
  CheckinDemoHouseRulesRoute: typeof CheckinDemoHouseRulesRoute
  CheckinDemoIdUploadRoute: typeof CheckinDemoIdUploadRoute
  CheckinDemoReviewRoute: typeof CheckinDemoReviewRoute
  CheckinDemoStartRoute: typeof CheckinDemoStartRoute
  CheckinDemoSubmittedRoute: typeof CheckinDemoSubmittedRoute
  OwnerSubmissionsIdRoute: typeof OwnerSubmissionsIdRoute
  OwnerSubmissionsIndexRoute: typeof OwnerSubmissionsIndexRoute
  CheckinDemoSurchargeIdRoute: typeof CheckinDemoSurchargeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/login': {
      id: '/owner/login'
      path: '/owner/login'
      fullPath: '/owner/login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/submissions/': {
      id: '/owner/submissions/'
      path: '/owner/submissions'
      fullPath: '/owner/submissions/'
      preLoaderRoute: typeof OwnerSubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings/': {
      id: '/owner/settings/'
      path: '/'
      fullPath: '/owner/settings/'
      preLoaderRoute: typeof OwnerSettingsIndexRouteImport
      parentRoute: typeof OwnerSettingsRoute
    }
    '/owner/submissions/$id': {
      id: '/owner/submissions/$id'
      path: '/owner/submissions/$id'
      fullPath: '/owner/submissions/$id'
      preLoaderRoute: typeof OwnerSubmissionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings/rooms': {
      id: '/owner/settings/rooms'
      path: '/rooms'
      fullPath: '/owner/settings/rooms'
      preLoaderRoute: typeof OwnerSettingsRoomsRouteImport
      parentRoute: typeof OwnerSettingsRoute
    }
    '/owner/settings/property': {
      id: '/owner/settings/property'
      path: '/property'
      fullPath: '/owner/settings/property'
      preLoaderRoute: typeof OwnerSettingsPropertyRouteImport
      parentRoute: typeof OwnerSettingsRoute
    }
    '/owner/settings/payments': {
      id: '/owner/settings/payments'
      path: '/payments'
      fullPath: '/owner/settings/payments'
      preLoaderRoute: typeof OwnerSettingsPaymentsRouteImport
      parentRoute: typeof OwnerSettingsRoute
    }
    '/owner/settings/passwords': {
      id: '/owner/settings/passwords'
      path: '/passwords'
      fullPath: '/owner/settings/passwords'
      preLoaderRoute: typeof OwnerSettingsPasswordsRouteImport
      parentRoute: typeof OwnerSettingsRoute
    }
    '/owner/settings/house-rules': {
      id: '/owner/settings/house-rules'
      path: '/house-rules'
      fullPath: '/owner/settings/house-rules'
      preLoaderRoute: typeof OwnerSettingsHouseRulesRouteImport
      parentRoute: typeof OwnerSettingsRoute
    }
    '/owner/settings/guide': {
      id: '/owner/settings/guide'
      path: '/guide'
      fullPath: '/owner/settings/guide'
      preLoaderRoute: typeof OwnerSettingsGuideRouteImport
      parentRoute: typeof OwnerSettingsRoute
    }
    '/owner/settings/faq': {
      id: '/owner/settings/faq'
      path: '/faq'
      fullPath: '/owner/settings/faq'
      preLoaderRoute: typeof OwnerSettingsFaqRouteImport
      parentRoute: typeof OwnerSettingsRoute
    }
    '/owner/settings/extra-fees': {
      id: '/owner/settings/extra-fees'
      path: '/extra-fees'
      fullPath: '/owner/settings/extra-fees'
      preLoaderRoute: typeof OwnerSettingsExtraFeesRouteImport
      parentRoute: typeof OwnerSettingsRoute
    }
    '/owner/settings/deposit': {
      id: '/owner/settings/deposit'
      path: '/deposit'
      fullPath: '/owner/settings/deposit'
      preLoaderRoute: typeof OwnerSettingsDepositRouteImport
      parentRoute: typeof OwnerSettingsRoute
    }
    '/checkin/demo/submitted': {
      id: '/checkin/demo/submitted'
      path: '/checkin/demo/submitted'
      fullPath: '/checkin/demo/submitted'
      preLoaderRoute: typeof CheckinDemoSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/demo/start': {
      id: '/checkin/demo/start'
      path: '/checkin/demo/start'
      fullPath: '/checkin/demo/start'
      preLoaderRoute: typeof CheckinDemoStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/demo/review': {
      id: '/checkin/demo/review'
      path: '/checkin/demo/review'
      fullPath: '/checkin/demo/review'
      preLoaderRoute: typeof CheckinDemoReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/demo/id-upload': {
      id: '/checkin/demo/id-upload'
      path: '/checkin/demo/id-upload'
      fullPath: '/checkin/demo/id-upload'
      preLoaderRoute: typeof CheckinDemoIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/demo/house-rules': {
      id: '/checkin/demo/house-rules'
      path: '/checkin/demo/house-rules'
      fullPath: '/checkin/demo/house-rules'
      preLoaderRoute: typeof CheckinDemoHouseRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/demo/home': {
      id: '/checkin/demo/home'
      path: '/checkin/demo/home'
      fullPath: '/checkin/demo/home'
      preLoaderRoute: typeof CheckinDemoHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/demo/guide': {
      id: '/checkin/demo/guide'
      path: '/checkin/demo/guide'
      fullPath: '/checkin/demo/guide'
      preLoaderRoute: typeof CheckinDemoGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/demo/guest-info': {
      id: '/checkin/demo/guest-info'
      path: '/checkin/demo/guest-info'
      fullPath: '/checkin/demo/guest-info'
      preLoaderRoute: typeof CheckinDemoGuestInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/demo/faq': {
      id: '/checkin/demo/faq'
      path: '/checkin/demo/faq'
      fullPath: '/checkin/demo/faq'
      preLoaderRoute: typeof CheckinDemoFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/demo/deposit': {
      id: '/checkin/demo/deposit'
      path: '/checkin/demo/deposit'
      fullPath: '/checkin/demo/deposit'
      preLoaderRoute: typeof CheckinDemoDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/demo/booking': {
      id: '/checkin/demo/booking'
      path: '/checkin/demo/booking'
      fullPath: '/checkin/demo/booking'
      preLoaderRoute: typeof CheckinDemoBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/demo/surcharge/$id': {
      id: '/checkin/demo/surcharge/$id'
      path: '/checkin/demo/surcharge/$id'
      fullPath: '/checkin/demo/surcharge/$id'
      preLoaderRoute: typeof CheckinDemoSurchargeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OwnerSettingsRouteChildren {
  OwnerSettingsDepositRoute: typeof OwnerSettingsDepositRoute
  OwnerSettingsExtraFeesRoute: typeof OwnerSettingsExtraFeesRoute
  OwnerSettingsFaqRoute: typeof OwnerSettingsFaqRoute
  OwnerSettingsGuideRoute: typeof OwnerSettingsGuideRoute
  OwnerSettingsHouseRulesRoute: typeof OwnerSettingsHouseRulesRoute
  OwnerSettingsPasswordsRoute: typeof OwnerSettingsPasswordsRoute
  OwnerSettingsPaymentsRoute: typeof OwnerSettingsPaymentsRoute
  OwnerSettingsPropertyRoute: typeof OwnerSettingsPropertyRoute
  OwnerSettingsRoomsRoute: typeof OwnerSettingsRoomsRoute
  OwnerSettingsIndexRoute: typeof OwnerSettingsIndexRoute
}

const OwnerSettingsRouteChildren: OwnerSettingsRouteChildren = {
  OwnerSettingsDepositRoute: OwnerSettingsDepositRoute,
  OwnerSettingsExtraFeesRoute: OwnerSettingsExtraFeesRoute,
  OwnerSettingsFaqRoute: OwnerSettingsFaqRoute,
  OwnerSettingsGuideRoute: OwnerSettingsGuideRoute,
  OwnerSettingsHouseRulesRoute: OwnerSettingsHouseRulesRoute,
  OwnerSettingsPasswordsRoute: OwnerSettingsPasswordsRoute,
  OwnerSettingsPaymentsRoute: OwnerSettingsPaymentsRoute,
  OwnerSettingsPropertyRoute: OwnerSettingsPropertyRoute,
  OwnerSettingsRoomsRoute: OwnerSettingsRoomsRoute,
  OwnerSettingsIndexRoute: OwnerSettingsIndexRoute,
}

const OwnerSettingsRouteWithChildren = OwnerSettingsRoute._addFileChildren(
  OwnerSettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerLoginRoute: OwnerLoginRoute,
  OwnerSettingsRoute: OwnerSettingsRouteWithChildren,
  OwnerIndexRoute: OwnerIndexRoute,
  CheckinDemoBookingRoute: CheckinDemoBookingRoute,
  CheckinDemoDepositRoute: CheckinDemoDepositRoute,
  CheckinDemoFaqRoute: CheckinDemoFaqRoute,
  CheckinDemoGuestInfoRoute: CheckinDemoGuestInfoRoute,
  CheckinDemoGuideRoute: CheckinDemoGuideRoute,
  CheckinDemoHomeRoute: CheckinDemoHomeRoute,
  CheckinDemoHouseRulesRoute: CheckinDemoHouseRulesRoute,
  CheckinDemoIdUploadRoute: CheckinDemoIdUploadRoute,
  CheckinDemoReviewRoute: CheckinDemoReviewRoute,
  CheckinDemoStartRoute: CheckinDemoStartRoute,
  CheckinDemoSubmittedRoute: CheckinDemoSubmittedRoute,
  OwnerSubmissionsIdRoute: OwnerSubmissionsIdRoute,
  OwnerSubmissionsIndexRoute: OwnerSubmissionsIndexRoute,
  CheckinDemoSurchargeIdRoute: CheckinDemoSurchargeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
